services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    env_file:
      - ../server/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  client:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.client
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  mongo_data:
