FROM node:20-slim AS build
WORKDIR /app
COPY client/package*.json ./
RUN npm install --no-fund --no-audit
COPY client/ .
RUN npm run build

FROM nginx:stable
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf