FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY server/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY server/ /app/
CMD ["python", "app.py"]
